path: '/players/{uuid}/{YY}/{MM}/{DD}.yml'
vein-distance: 3 # max distance between last and current location mined to be considered a vein
UI:
    years:
        material: DIAMOND
        2022: CHEST
    months:
        material: CHEST
        1: PAPER
        2: OAK_WOOD
    days:
        material: PAPER
        1: PAPER
    colors:
        DIAMOND_ORE: '&b'
        GOLD_ORE: '&6'
        LAPIS_ORE: '&1'
        EMERALD_ORE: '&a'
        COPPER_ORE: '&2'
        COAL_ORE: '&7'
        REDSTONE_ORE: '&c'
        IRON_ORE: '&e'
messages:
    0: '&7[&aMyLog&7]&r'
    1: '{prefix} &aAdded&r to log list.'
    2: '{prefix} &cRemoved&r from log list.'
    3: '{prefix} &cInvalid command args!'
    4: '{prefix} &cPage not found!'
    5: '{prefix} &cRemoved from debug.'
    6: '{prefix} &aAdded to debug.'
    7: '{prefix} &cYou do not have permission for this command.'
    8: "{prefix} Viewing &a{target}'s&r logs."
    9: "{prefix} Couldn't find '&c{target}&r'!"
    10: "Only players can run this command!"
    11: "{prefix} &aConfigs reloaded."
    12: "{prefix} &a{player}&r mined {color}{blocktype}&r at {xyz}"